<a href="https://colab.research.google.com/github/samitha278/EN3160-IPCV/blob/main/spatial_filtering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import cv2
import matplotlib.pyplot as plt

## Convolution

In [15]:
torch.manual_seed(278)
image = torch.randn((12,12)).view(1,1,12,12)
kernel = (1/9) * torch.ones((3,3)).view(1,1,3,3)
image,kernel

(tensor([[[[-0.3113, -1.6257, -0.4428,  0.7869, -2.3081, -2.4534,  2.5515,
             1.5013, -0.4279,  0.0149,  0.6168,  2.5252],
           [-0.4348,  1.8983, -0.4243,  1.1160,  1.3476, -1.8999,  0.2999,
             2.0132, -0.0537,  0.0273, -0.9289,  2.4260],
           [ 0.5965, -0.9634,  0.6497,  0.3516, -0.5396,  0.5949, -0.8981,
             1.1714, -0.2333,  0.9272,  1.0551,  0.7002],
           [-0.7530,  0.3305, -1.3149, -0.8310, -0.9323, -0.2117,  0.3902,
             0.9124, -0.6891,  0.4506,  3.0519, -0.5101],
           [-0.3543,  2.1348,  1.1454,  0.4737, -0.6503,  2.7713, -1.4388,
             1.0588, -1.2221, -0.6614, -2.8858, -0.3586],
           [-0.3820, -1.2520,  0.3543,  1.0647,  0.1902,  0.0061, -0.1596,
            -0.1823,  0.1748, -0.0332,  1.1809,  1.9225],
           [-0.1120,  1.1314, -0.1735, -0.5383, -2.2424, -0.7450, -1.2321,
            -0.8446,  0.6800,  1.0753,  0.1750,  0.8562],
           [ 2.9217, -0.5220,  2.1552,  2.1454, -2.8136, -0.4572,  0.

In [16]:
out = F.conv2d(image,kernel)
out

tensor([[[[-0.1175,  0.1496,  0.0597, -0.3338, -0.3673,  0.3201,  0.6582,
            0.5489,  0.1108,  0.8182],
          [-0.0462,  0.0903, -0.0641, -0.1116, -0.2054,  0.2636,  0.3237,
            0.5029,  0.4008,  0.7999],
          [ 0.1635,  0.2196, -0.1831,  0.1141, -0.1016,  0.4834, -0.1054,
            0.1905, -0.0230,  0.1966],
          [-0.0101,  0.2340, -0.0556,  0.2090, -0.0039,  0.3496, -0.1284,
           -0.0213, -0.0704,  0.2397],
          [ 0.2769,  0.4823, -0.0418,  0.0367, -0.3889, -0.0851, -0.3517,
            0.0050, -0.1685,  0.1412],
          [ 0.4579,  0.4850,  0.0158, -0.3767, -0.7614, -0.4318, -0.3254,
           -0.2359,  0.1920,  0.7521],
          [ 1.0544,  0.9214,  0.0025, -0.4659, -0.8134, -0.3911, -0.3449,
           -0.2776,  0.0544,  0.3603],
          [ 0.7850,  0.8552,  0.5037,  0.2075, -0.2416,  0.0780, -0.2340,
           -0.2871, -0.1974,  0.1756],
          [ 0.2737,  0.4367,  0.3030,  0.1641,  0.0570,  0.2981,  0.2200,
            0.3020,  0

In [17]:
conv_layer = nn.Conv2d(1,1,3)
out1 = conv_layer(image)
out1

tensor([[[[-0.6002,  0.4324,  0.0376, -0.3768,  0.6473, -0.5791,  1.0110,
            0.0100, -0.0567,  0.3127],
          [ 1.1145,  0.7050,  0.9131,  0.8844,  0.4859,  0.0576,  0.3548,
            0.3961, -0.5150,  0.5105],
          [ 0.0825, -0.5094,  0.2415, -0.6021,  0.9562, -0.8187,  0.8625,
            0.5409,  1.7341,  0.3179],
          [-0.1685,  0.3248, -0.2464,  0.0728, -0.4052,  0.7466,  0.0554,
            0.6922, -0.3043,  0.2665],
          [ 0.6795,  0.5847,  1.1192,  0.8102,  1.2331,  1.2862,  0.1379,
            0.3518, -0.2460, -0.5739],
          [-1.5949, -0.2616,  0.5861,  0.0422,  0.8860,  0.7681,  0.4696,
            0.7540,  0.3974,  0.2529],
          [-0.3570, -0.1415, -0.3032, -0.3845,  0.2530,  0.0034, -0.3466,
            0.6109,  0.7043,  0.3888],
          [ 1.1994,  0.5125,  0.0993,  0.4032, -0.2016, -0.8240,  1.0873,
           -0.4686,  0.0710,  0.1843],
          [ 0.9594,  0.6905,  0.4879,  1.0520, -0.5398,  0.6229, -0.2813,
           -0.3000, -0